services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Secret: "ChangeThisDockerSecretToARealLongRandomValue123!"
      Jwt__Issuer: "TravelAgency.Api"
      Jwt__Audience: "TravelAgency.Client"
      ConnectionStrings__CRUDCS: "Server=sqlserver,1433;Database=Travel_Agency;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true"
    ports:
      - "5132:8080"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
