apiVersion: 1

datasources:
  - name: Travel Agency Prometheus
    uid: travel-agency-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
