apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - redis.yaml
  - rabbitmq.yaml
  - sqlserver.yaml
  - api-deployment.yaml
  - api-hpa.yaml
  - notification-service-deployment.yaml
  - ingress.yaml
  - backup-cronjob.yaml
