apiVersion: v1
kind: Secret
metadata:
  name: travel-agency-secrets
  namespace: travel-agency
type: Opaque
stringData:
  Jwt__Secret: "replace-with-long-random-secret"
  ConnectionStrings__CRUDCS: "Server=sqlserver,1433;Database=Travel_Agency;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true"
  Email__Smtp__Username: ""
  Email__Smtp__Password: ""
  Alerting__SlackWebhookUrl: ""
  Alerting__Email__To: ""
  Storage__S3__AccessKey: "minioadmin"
  Storage__S3__SecretKey: "minioadmin"
  MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
